### ISSUE TITLE
Find and fix flaky apollo-cli test that causes checks to fail

### ISSUE THREAD

**Issue by Enrico2** [apollographql/rust#63]
Reproducible locally:

```
cargo install flaky-finder
flaky-finder -j8 -r20 "cargo test -p apollo-cli"
```

This might contain one of the reasons:
https://github.com/apollographql/rust/pull/60/checks?check_run_id=773610533

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NetworkError', cli/src/version.rs:94:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: core::result::Result<T,E>::unwrap
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/result.rs:1005
  15: apollo_cli::version::get_latest_release
             at cli/src/version.rs:94
  16: apollo_cli::version::needs_updating
             at cli/src/version.rs:173
  17: apollo_cli::version::background_check_for_updates::{{closure}}
             at cli/src/version.rs:201
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread panicked while panicking. aborting.

```

**Comment by Enrico2** [comment]
This backtrace points to the problem being with one of the unwrap calls in `get_latest_release` -- generally speaking though, there are too many calls to unwrap instead of propagating or handling appropriately.

**Comment by Enrico2** [comment]
For future reference and some education, I'll do my best to document the process I went through to get to where I am now.

## First, the backtrace above
That one was actually new, when we had flaky tests before, we didn't see a backtrace, we usually saw "thread panicked while panicking". So I started from going to where the backtrace pointed me towards, and saw we `.unwrap` on an HTTP request, that could definitely fail for various reasons. A failure there should propagate as a `Fallible` rather than panic, so I refactored that code a little bit, to return `Fallible` with the appropriate `ErrorDetails` that will eventually resolve to returning the expected error code. Since the function now returns `Fallible`, we don't need to convert the `Err` case in call sites to an `ApolloError`.

There are a couple of reasons this could fail, but at this point I only thought of one, because I was less familiar with the code: _"A real network issue if we're running integration tests that make real http requests."_

So, this could still fail, in case there's a real network error, the flakiness of this is very rare and is kind of out of our hands, assuming integration tests make real HTTP requests. There is a second reason this could fail, that I didn't realize until later, at this point I was sure that the reason we rarely saw this backtrace, is because it's a rare but possible error. I'm trying to write this chronologically, so more on the real cause later.

I happened to find this one second...

## Second, attempting to read from a closed channel

When I first suspected concurrency issues, my brain kept going to the one place we have concurrent code: The update checker. 

Whenever one runs a CLI command, unless it's explicitly "update", we spawn a thread that checks if there's an update to the CLI in the background. 

I looked at this code from 7 different angles, I was sure this is probably the cause; running a thread without any synchronization mechanisms that ensure a predictable behavior are bound to _sometimes_ fail with tests, right? 

Our code specifically runs this update check as a best effort sort of thing; we spawn the thread to check for updates, then run the real command, then at the end of it, if there happens to be data in the channel sent to by the thread, we print out a message saying there's an update. If there is no message, we do nothing. There could be many reasons for which there will be no message. 
Running the tests many times, when they failed, it was in the same spot: calling `.unwrap()` in the first use case in `background_updates()` (spoiler, turns out this is probably also due to the third flakiness issue). I managed to print the error and it told me the problem was trying to read from a closed channel.

We create the channel in the function we invoke directly, it **moves** the sender to the thread, and returns the receiver. I went into the docs, turns out that a spawned thread needs stuff moved into it, or if using borrowed values, they need the `'static` lifetime, because a spawned thread may outlive its parent (unless it's the main thread, but idk what exactly happens with parallel test runs, not important though, just FYI). So, for a channel to be closed, the sender needs to have been destroyed, which I think meant that the thread finished running. It's completely possible that _sometimes_ the thread may finish its code before we even check the receiver, in which case we'll get the error I observed.

I changed the code to (1) clone the sender and send the clone to the thread and (2) return both sender and receiver from the function so that the sender and receiver will have the same lifetime. 

Looking into the docs of [channel()](https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html), I saw the senders can be cloned and that they'll still send to the same receiver. Receivers cannot be cloned.

So I did that, but I also ensured to not leave any trailing branches in the thread code (it only sent to the channel if some conditions were met, otherwise it did nothing and finished). I changed the channel type to contain `Option<Version>` and sent a `None` in all branches to ensure we always send something before the thread finishes, so there's anyways _some message_ in the channel. I might refactor this later, because, once I did that, I still had a flaky test! This time it was a different `.unwrap()` in a test than before.. Will this never end? 

So then I found the third, and what I hope to the be final reason, once I found it, it explained the issue with both of the previous failures..

## Third, The `APOLLO_CDN_URL` environment variable

This was a little trickier to find, first let's start with how I found the problem.

The tests were failing locally on my mac, but not every time, I installed a tool called "flaky-finder" (`cargo install flaky-finder`), it's a simple utility that allows you to run a command many times in parallel over a chosen amount of threads.
From looking at all of our failing CI tests, I saw we fail when we run `apollo-cli` tests (this is a monorepo, we run all tests for all packages). So I ran this with flaky-finder:
```
flaky-finder -j8 -r20 -p --continue "RUST_BACKTRACE=1 cargo test -p apollo-cli"
```
This is what the arguments mean:
```
$ flaky-finder --help
Flaky-Finder 0.2.22
dymayday <dymayday@gmail.com>
This app is looking for flakyness in tests in the matrix.

USAGE:
    flaky-finder [FLAGS] [OPTIONS] <"cmd">

FLAGS:
    -c, --continue                  Whether or not we want to stop at the fist error found.
    -h, --help                      Prints help information
    -p, --print-error-on-the-fly    Show errors as they arrive of show them as a summary at the end.
    -V, --version                   Prints version information

OPTIONS:
    -j <nb_threads>        The number of threads we want to run test harness. [default: 1]
    -r <runs>              Perform exactly NUM runs for the command. [default: 10]

ARGS:
    <"cmd">    The command of the process we want to evaluate.
```
After about 4-5 runs, there was usually a failure, but it still didn't print anything interesting apart from `thread panicked when panicking`, and so I added `println!`s in the code. Still nothing, so I changed them to `eprintln!`, and still nothing. Then I remembered there's a special flag to tell the test runner to **not capture** std out/err, I changed my command to 
```
flaky-finder -j8 -r20 -p --continue "RUST_BACKTRACE=1 cargo test -p apollo-cli -- --nocapture"
```
and yes, at least I got prints! But alas, the failure was just saying that an `.unwrap` was called from test code and printed `Unable to fetch release`, we have that message on `ReleaseFetchError` .. but ... we return that error in 8 places, and I didn't know which one was the cause. You see, it seems the backtrace stems from the `unwrap`, which is the thing that panics. It doesn't show the propagation of `Result` through the call stack.

So I changed this
```
#[error("Unable to fetch release")]
ReleaseFetchError,
```
to this:
```
#[error("Unable to fetch release", .msg)]
ReleaseFetchError { msg: String },
```

And in the 8 places we use this error, I put in a different message.
I ran `flaky-finder` again and found the specific location of the error we're seeing, turns out it was being thrown in a case where `!resp.status().is_success()` and because I knew which test is failing (the one calling `.unwrap()`), I knew we're using a mock server there.

We have some tests that set up a mock http server using [wiremock](https://docs.rs/wiremock/0.2.2/wiremock/struct.MockServer.html). Our **non test code** gets the url to use from the `APOLLO_CDN_URL` environment variable, the tests spin up the mock server, get _its url_, override `APOLLO_CDN_URL` with it, and test the code. 

It was not at all clear to me why the mocking code would not work and result in a non successful response, and only occasionally.
Because interestingly, @jbaxleyiii thought about this issue, and put all of the tests in `version.rs` in a single test function so that they'll all run in one thread, however, he even commented
```
// environment variables are a shared resource on the thread so we combine these tests
// together to prevent url clobbering
```
I spent some time digging into how the mocking thing works, read its docs, [complained on slack](https://meteor.slack.com/archives/C013EMYJ48J/p1592264063014000), yada yada.

I kept changing stuff here and there, trying to comment out code that I thought might affect parallel runs, nothing really worked but this is where I got lucky! I noticed one of the tests that failed is not in `version.rs`, but rather in `session.rs`, I looked into that code and saw that we use the mocking server there too, at first this led me down the wrong path, as I thought it was further validation that the mock server framework is defecating the bed. So I thought, well, if the response is not successful, WHAT is it returning if not a 200? I added prints where we check the http response, and viola:
```
response status is 404 Not Found, res is Response { url: "http://127.0.0.1:8001/cli/darwin", status: 404, headers: {"content-length": "0", "date": "Tue, 16 Jun 2020 00:08:10 GMT"} }
response status is 200 OK, res is Response { url: "http://127.0.0.1:8001/telemetry", status: 200, headers: {"content-length": "0", "date": "Tue, 16 Jun 2020 00:08:10 GMT"} }
```
Every time we fail, we also print a success on the other endpoint, but with the same host:port! Hold on, I thought, why is this the same url? The docs for wiremock say that test isolation is a feature, and that it's safe to spin up separate mock servers in different tests running in parallel, that the server will grab an available port, but every time I saw those prints, it was the same port! 
Looking more into the docs, I saw that if one does not mock an endpoint, it will return a 404, which led me to understand that a test is using a mock server from another test! How is that possible?? ... oh right, environment variable.

So, this is where I'm at now, and this has to be the reason:
2 tests running in parallel, `session.rs` and `version.rs` are spinning up mock servers, both overriding the same environment variable, and there's a race condition that _sometimes_ fails the tests because we get an unexpected 404.

I'll figure out the best way to fix this, I suspect I'll end up passing the url as an argument to a function that will only be used _directly_ by tests, the "real" function will get the environment variable value and pass it down.


## Summary

So, the first case, where I thought the problem was a real network error? Probably not, we probably hit another random case of the race condition and attempted to call a mock server set up in a different test, which resulted in a failure.

The 2nd case is real, we were trying to read from a closed channel, the way the code is written can certainly cause that, I suspect we didn't see it because we barely have any CLI commands that take longer than the update check, and so we check the channel before it's closed. But because we failed fast in the async update check, again due to the race with the url, that thread was done super quickly, and we checked the channel AFTER the it was closed.

Once fixing the channel stuff, I only remaining error was the root of it all. (I hope)

**Comment by Enrico2** [comment]
## Update:

After fixing the bug, I reverted the changes to `background_check_for_updates`, and I'm letting the `sender` either die in the thread or send a `Version` (not an `Option`). After reviewing the code and tests, this was good before.

I tested locally that sending a message to a channel, then the sender being destroyed doesn't prevent the receiver from getting the message.

```
use std::sync::mpsc::{channel, Receiver};
fn foo() -> Receiver<u32> {
    let (sender, receiver) = channel::<u32>();
    let _ = sender.send(3);
    receiver
}
let receiver = foo();
println!("{:?}", receiver.try_recv());
println!("{:?}", receiver.try_recv());
```

prints
```
Ok(3)
Err(Disconnected)
```

And so before, it was ok for us to only send a message if we hit a specific case in the branch, since we use `try_recv()` we (1) do not block and (2) handle all errors appropriately.

The tests use `recv()` in order to _block_ and expect either a success or a failure. So that's ok.
